/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.97.2
  Forc version: 0.66.5
  Fuel-Core version: 0.40.1
*/

import {
  Account,
  BigNumberish,
  BN,
  decompressBytecode,
  Script,
} from 'fuels';

export type TestScriptInputs = [input: BigNumberish];
export type TestScriptOutput = BN;

const abi = {
  "programType": "script",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "input",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA01SMW/TQBT+EixhsXCAi6IrhQymyhgJBqADd7Ijx7SIi4gEi3HZGCMLoY75CTAAHRkZzxIDo0fGjoxekWqJpVKqDul3bqPUy/vuu/e+997nk/+H+Ah4aL/ubBWzZdURyyXkscEXdIV5XZr3CjfyBs8ZPcanJioXJrGzYgx/MPLmZrfcLxRxGoB3f4uYWIcqi+xOpgHWaIcdvxkHSmhPkdshp6lzQHyTdR9aPR3MTVKutaPyaMUz/5n8B/QXj/D2rO6as9rjDu9kdOR6uH6qiD1sx4CMZzC79jBvxB3HMQb5MTY4Q2/QhIp9/1C3N0h+ufkPij3iNKjYu9/iUVixvrfm7XzFZ2+syF7ZW1lib7vZRBrMN9Kw+jRGh/NcJ9fdTB+7fF+8DKvtPWCwNVVyOoNIpypPAeeX0PQrsXXemHt5M9ziDvdNZIftXBc++C2+8OHzFb6+wtc8P1mf7XidZ+2Kpzd3zUgI7rRgnwdG9303H/Mq1uzTF+H+GbV+skZcav9uMbXa+4mnMq062UTh4QT4Clz75tNrvhUZ/YBMasgTnk8FDsl/5/2LBZDwZZ0Dnd0OEXACAAA=');

export class TestScript extends Script<TestScriptInputs, TestScriptOutput> {

  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(wallet: Account) {
    super(bytecode, abi, wallet);
  }
}
