/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.97.2
  Forc version: 0.66.5
  Fuel-Core version: 0.40.1
*/

import {
  BigNumberish,
  BN,
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type TestPredicateLoaderConfigurables = undefined;

export type TestPredicateLoaderInputs = [password: BigNumberish];

export type TestPredicateLoaderParameters = Omit<
  PredicateParams<TestPredicateLoaderInputs, TestPredicateLoaderConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "password",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " This predicate checks if the given password is 1337."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " If it is, the predicate is 'unlocked' and the transaction is allowed to proceed."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Otherwise, it is reverted."
          ]
        }
      ]
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA5NyMGAIcGRQkHIJYNjlycBg5MDSqOAqzBDkKsDi5cLA8GQpXytjYD3bKVk2qR+7WL/JL9bybFjKfSBra0iolvJBeQA2SrnQQAAAAA==');

export class TestPredicateLoader extends Predicate<
  TestPredicateLoaderInputs,
  TestPredicateLoaderConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: TestPredicateLoaderParameters) {
    super({ abi, bytecode, ...params });
  }
}
